### ISSUE TITLE
tarea 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/mapa-mental-yaritzaov123#2]
[MAPA MENTSL.docx](https://github.com/SistemasTecTlaxiaco/mapa-mental-yaritzaov123/files/7287409/MAPA.MENTSL.docx)

**Comment by isaireyesp1** [comment]
Manejo conceptual y dominio del tema (orden, jerarquía, aspecto visual y conceptos): (notable)
Relación entre los conceptos incluidos en el mapa: (excelente)
Calidad de la presentación: (notable)
Jerarquía: (excelente)
Total: 94/100
Calificación: 18.8% / 20%
Calificado por: Isai Reyes Peña

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
